### ISSUE TITLE
Unexpected end of expression Error

### ISSUE THREAD

**Issue by jazarja** [rajeshwarpatlolla/ionic-datepicker#23]
I have follow the instruction to install ionic-datepicker, but when I try to click the datepicker, the following error was thrown on my browser javascript console

```
Error: [$parse:ueoe] Unexpected end of expression: dateSelected(dayList
http://errors.angularjs.org/1.3.13/$parse/ueoe?p0=dateSelected(dayList
    at REGEX_STRING_REGEXP (http://localhost:8100/lib/ionic/release/js/ionic.bundle.js:8762:12)
    at Parser.consume (http://localhost:8100/lib/ionic/release/js/ionic.bundle.js:20747:13)
    at Parser.functionCall (http://localhost:8100/lib/ionic/release/js/ionic.bundle.js:21022:10)
    at Parser.primary (http://localhost:8100/lib/ionic/release/js/ionic.bundle.js:20694:24)
    at Parser.unary (http://localhost:8100/lib/ionic/release/js/ionic.bundle.js:20970:19)
    at Parser.multiplicative (http://localhost:8100/lib/ionic/release/js/ionic.bundle.js:20953:21)
    at Parser.additive (http://localhost:8100/lib/ionic/release/js/ionic.bundle.js:20944:21)
    at Parser.relational (http://localhost:8100/lib/ionic/release/js/ionic.bundle.js:20935:21)
    at Parser.equality (http://localhost:8100/lib/ionic/release/js/ionic.bundle.js:20926:21)
    at Parser.logicalAND (http://localhost:8100/lib/ionic/release/js/ionic.bundle.js:20917:21) <div class="date_cell ng-binding" ng-click="dateSelected(dayList[$parent.$index * numColumns + $index])" ng-class="{'pointer_events_none':(disablePreviousDates &amp;&amp; previousDayEpoch >(anonymous function)
```

Any idea how to solve this?

**Comment by rajeshwarpatlolla** [comment]
Could you please share me the of html and your controller. I just want to have a look at the way you are using this component. I tested it well and was working fine.

**Comment by campsjos** [comment]
I've got the same error and solved it setting the attributes in the right order: `ipDate`, `disablePreviousDates` and `callback`.
I lost a large amount of time with this... Hope it helps somebody!

**Comment by rajeshwarpatlolla** [comment]
Thanks @campsjos.
